# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'friendship_UI.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(711, 695)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(500, 600, 161, 41))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.pushButton_clear = QtWidgets.QPushButton(self.formLayoutWidget_7)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_clear)
        self.pushButton_close = QtWidgets.QPushButton(self.formLayoutWidget_7)
        self.pushButton_close.setObjectName("pushButton_close")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_close)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 641, 541))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_add = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_add.setObjectName("groupBox_add")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_add)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 40, 161, 85))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_name_input = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_name_input.setObjectName("label_name_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name_input)
        self.lineEdit_name_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_name_input.setObjectName("lineEdit_name_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name_input)
        self.label_sno_input = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_sno_input.setObjectName("label_sno_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_sno_input)
        self.lineEdit_sno_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_sno_input.setObjectName("lineEdit_sno_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sno_input)
        self.label_birthday_input = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_birthday_input.setObjectName("label_birthday_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_birthday_input)
        self.lineEdit_birthday_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_birthday_input.setObjectName("lineEdit_birthday_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_birthday_input)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_add)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(250, 40, 171, 81))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_sex_input = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_sex_input.setObjectName("label_sex_input")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_sex_input)
        self.label_pos_input = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_pos_input.setObjectName("label_pos_input")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_pos_input)
        self.comboBox_sex_input = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_sex_input.setObjectName("comboBox_sex_input")
        self.comboBox_sex_input.addItem("")
        self.comboBox_sex_input.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_sex_input)
        self.lineEdit_pos_input = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_pos_input.setObjectName("lineEdit_pos_input")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pos_input)
        self.pushButton_add_input = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_add_input.setObjectName("pushButton_add_input")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_add_input)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_add)
        self.layoutWidget1.setGeometry(QtCore.QRect(470, 30, 94, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_pic_input = QtWidgets.QLabel(self.layoutWidget1)
        self.label_pic_input.setStyleSheet("background-color:white;\n"
"border-color:#FFFFFF;")
        self.label_pic_input.setText("")
        self.label_pic_input.setObjectName("label_pic_input")
        self.verticalLayout_2.addWidget(self.label_pic_input)
        self.pushButton_upload_input = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_upload_input.setObjectName("pushButton_upload_input")
        self.verticalLayout_2.addWidget(self.pushButton_upload_input)
        self.verticalLayout.addWidget(self.groupBox_add)
        self.groupBox_search = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_search.setObjectName("groupBox_search")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_search)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(270, 40, 160, 85))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_sno_find = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_sno_find.setObjectName("label_sno_find")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_sno_find)
        self.lineEdit_sno_find = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_sno_find.setReadOnly(True)
        self.lineEdit_sno_find.setObjectName("lineEdit_sno_find")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sno_find)
        self.label_birthday_find = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_birthday_find.setObjectName("label_birthday_find")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_birthday_find)
        self.lineEdit_birthday_find = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_birthday_find.setReadOnly(True)
        self.lineEdit_birthday_find.setObjectName("lineEdit_birthday_find")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_birthday_find)
        self.label_sex_find = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_sex_find.setObjectName("label_sex_find")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_sex_find)
        self.lineEdit_sex_find = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_sex_find.setReadOnly(True)
        self.lineEdit_sex_find.setObjectName("lineEdit_sex_find")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sex_find)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_search)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(40, 40, 160, 92))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_name_search = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_name_search.setObjectName("label_name_search")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name_search)
        self.label_name_find = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_name_find.setObjectName("label_name_find")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_name_find)
        self.lineEdit_name_find = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_name_find.setReadOnly(True)
        self.lineEdit_name_find.setObjectName("lineEdit_name_find")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name_find)
        self.pushButton_search = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.pushButton_search.setObjectName("pushButton_search")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_search)
        self.lineEdit_name_search = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_name_search.setObjectName("lineEdit_name_search")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name_search)
        self.label_pic_find = QtWidgets.QLabel(self.groupBox_search)
        self.label_pic_find.setGeometry(QtCore.QRect(470, 30, 91, 101))
        self.label_pic_find.setStyleSheet("background-color:white;\n"
"")
        self.label_pic_find.setText("")
        self.label_pic_find.setObjectName("label_pic_find")
        self.verticalLayout.addWidget(self.groupBox_search)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_delete = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_delete.setObjectName("groupBox_delete")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_delete)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(40, 20, 160, 80))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_pos_delete = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_pos_delete.setObjectName("label_pos_delete")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_pos_delete)
        self.lineEdit_pos_delete = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.lineEdit_pos_delete.setObjectName("lineEdit_pos_delete")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pos_delete)
        self.pushButton_delete = QtWidgets.QPushButton(self.formLayoutWidget_5)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_delete)
        self.horizontalLayout.addWidget(self.groupBox_delete)
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(30, 20, 160, 80))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_num_info = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_num_info.setObjectName("label_num_info")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_num_info)
        self.lineEdit_num_info = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.lineEdit_num_info.setReadOnly(True)
        self.lineEdit_num_info.setObjectName("lineEdit_num_info")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_num_info)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 711, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_clear.setText(_translate("MainWindow", "清空链表"))
        self.pushButton_close.setText(_translate("MainWindow", "关闭"))
        self.groupBox_add.setTitle(_translate("MainWindow", "添加信息"))
        self.label_name_input.setText(_translate("MainWindow", "姓名"))
        self.label_sno_input.setText(_translate("MainWindow", "学号"))
        self.label_birthday_input.setText(_translate("MainWindow", "生日"))
        self.label_sex_input.setText(_translate("MainWindow", "性别"))
        self.label_pos_input.setText(_translate("MainWindow", "插入位置"))
        self.comboBox_sex_input.setItemText(0, _translate("MainWindow", "男"))
        self.comboBox_sex_input.setItemText(1, _translate("MainWindow", "女"))
        self.pushButton_add_input.setText(_translate("MainWindow", "添加"))
        self.pushButton_upload_input.setText(_translate("MainWindow", "上传照片"))
        self.groupBox_search.setTitle(_translate("MainWindow", "查找信息"))
        self.label_sno_find.setText(_translate("MainWindow", "学号"))
        self.label_birthday_find.setText(_translate("MainWindow", "生日"))
        self.label_sex_find.setText(_translate("MainWindow", "性别"))
        self.label_name_search.setText(_translate("MainWindow", "查找姓名"))
        self.label_name_find.setText(_translate("MainWindow", "姓名"))
        self.pushButton_search.setText(_translate("MainWindow", "查找"))
        self.groupBox_delete.setTitle(_translate("MainWindow", "删除信息"))
        self.label_pos_delete.setText(_translate("MainWindow", "删除位置"))
        self.pushButton_delete.setText(_translate("MainWindow", "删除"))
        self.groupBox_4.setTitle(_translate("MainWindow", "链表信息"))
        self.label_num_info.setText(_translate("MainWindow", "链表总人数"))


